////////////////////////////////////////
-- CONSULTAS DE COMBINACION DE DATOS --
////////////////////////////////////////

SELECT NOMBRE AS NOMBRES
FROM ESTUDIANTES
UNION
SELECT NOMBRE
FROM PROFESORES;
-- /*SE REALIZA UNA UNION DE DOS TABLAS, DONDE SE MUESTRAN LOS NOMBRES DE LOS ESTUDIANTES Y LOS PROFESORES*/

SELECT EMAIL AS correos_unicos 
FROM usuarios 
UNION
SELECT DISTINCT EMAIL 
FROM clientes;
-- /*SE REALIZA UNA UNION DE DOS TABLAS, DONDE SE MUESTRAN LOS CORREOS DE LOS USUARIOS Y LOS CLIENTES*/

SELECT * FROM empleados1
UNION ALL
SELECT * FROM empleados2;
-- /*SE REALIZA UNA UNION DE DOS TABLAS, DONDE SE MUESTRAN TODOS LOS DATOS DE LOS EMPLEADOS DE LAS DOS TABLAS, HASTA LOS QUE SE REPITEN*/

SELECT * FROM Lista1
INTERSECT
SELECT * FROM Lista2;
-- /*SE REALIZA UNA INTERSECCION DE DOS TABLAS, DONDE SE MUESTRAN LOS DATOS QUE SE REPITEN EN AMBAS TABLAS*/

SELECT NOMBRE FROM empleados
EXCEPT 
SELECT NOMBRE FROM gerentes;
-- /*SE REALIZA UNA EXCEPCION DE DOS TABLAS, DONDE SE MUESTRAN LOS DATOS QUE NO SE REPITEN EN AMBAS TABLAS*/