/////////////////////////////////////////
INSERT INTO
/////////////////////////////////////////

INSERT INTO usuarios 
VALUES (7, 'LUCÍA','SÁNCHEZ',
'luciasanchez@outlook.com', '555-5555');
/*SE INSERTA UN NUEVO USUARIO EN LA TABLA USUARIOS*/

INSERT INTO productos
VALUES (7, 'Bolso', 1000, 10);
/*SE INSERTA UN NUEVO PRODUCTO EN LA TABLA PRODUCTOS*/

INSERT INTO productos
VALUES(7, 'Bolso', 1000, NULL);
/*SE INSERTA UN NUEVO PRODUCTO EN LA TABLA PRODUCTOS, CON UN VALOR NULO EN LA COLUMNA CANTIDAD*/

INSERT INTO usuarios
(ID, APELLIDO, NOMBRE, TELEFONO, EMAIL)
VALUES(7, 'SÁNCHEZ', 'LUCÍA', '333-3333',
'luciasanchez@outlook.com' )
/*SE INSERTA UN NUEVO USUARIO EN LA TABLA USUARIOS, ESPECIFICANDO LAS COLUMNAS A LAS QUE SE LES ASIGNARÁN LOS VALORES*/

INSERT INTO productos 
(NOMBRE, STOCK)
VALUES('Bolso', 10);
/*SE INSERTA UN NUEVO PRODUCTO EN LA TABLA PRODUCTOS, ESPECIFICANDO LAS COLUMNAS A LAS QUE SE LES ASIGNARÁN LOS VALORES*/

INSERT INTO productos 
(NOMBRE, STOCK, FECHA)
VALUES ('Bolso', 10, CURRENT_DATE);
/*SE INSERTA UN NUEVO PRODUCTO EN LA TABLA PRODUCTOS, ESPECIFICANDO LAS COLUMNAS A LAS QUE SE LES ASIGNARÁN LOS VALORES, INCLUYENDO LA FECHA ACTUAL*/

INSERT INTO productos 
(NOMBRE, STOCK, FECHA)
VALUES ('Bolso', 10, '2023-01-01')
/*SE INSERTA UN NUEVO PRODUCTO EN LA TABLA PRODUCTOS, ESPECIFICANDO LAS COLUMNAS A LAS QUE SE LES ASIGNARÁN LOS VALORES, INCLUYENDO UNA FECHA ESPECÍFICA*/

INSERT INTO ventas VALUES ('GORRO', 5, 1000), ('CAMISETA', 10, 500), ('PANTALÓN', 8, 1500);
/*SE INSERTAN VARIOS REGISTROS EN LA TABLA VENTAS*/

INSERT INTO empleados
(NOMBRE, APELLIDO)
VALUES ('Jane', 'Smith')
RETURNING ID;
/*SE INSERTA UN NUEVO EMPLEADO EN LA TABLA EMPLEADOS, ESPECIFICANDO LAS COLUMNAS A LAS QUE SE LES ASIGNARÁN LOS VALORES Y SE RETORNA EL ID DEL NUEVO REGISTRO*/

INSERT INTO usuarios
(NOMBRE, APELLIDO, EMAIL)
VALUES ('LUCÍA', 'SÁNCHEZ', 'luciasanchez@outlook.com');
/*SE INSERTA UN NUEVO USUARIO EN LA TABLA USUARIOS, ESPECIFICANDO LAS COLUMNAS A LAS QUE SE LES ASIGNARÁN LOS VALORES, EN ESTE CASO HAY COLUMNAS LAS CUALES TOMAN UN VALOR PREDETERMINADO SI NO SE LE ASIGNA UN VALOR, EJ:TELEFONO E ID*/