////////////////////////////////////////
-- 1. RESTRICCIONES
////////////////////////////////////////

CREATE TABLE empleados
(NOMBRE TEXTE NOT NULL,
APELLIDO TEXT);
INSERT INTO empleados VALUES ('PEDRO', 'PÉREZ');
/*SE CREA UNA TABLA CON DOS CAMPOS, NOMBRE Y APELLIDO, Y SE INSERTA UN REGISTRO EN LA TABLA, HACIENDO QUE UN CAMPO NO SEA NULO*/

CREATE TABLE patentes2(
    PATENTE TEXT NOT NULL
);
INSERT INTO patentes2
SELECT PATENTE FROM patentes;
DROP TABLE patentes;
ALTER TABLE patentes2 RENAME TO patentes;
/*SE CREA UNA TABLA CON UN CAMPO, PATENTE, Y SE INSERTAN LOS DATOS DE LA TABLA PATENTES EN LA TABLA PATENTES2, LUEGO SE ELIMINA LA TABLA PATENTES Y SE RENOMBRA LA TABLA PATENTES2 A PATENTES*/

CREATE TABLE personas2 (
    nombre TEXT,
    apellido TEXT,
    edad INTEGER
);
INSERT INTO personas2 (nombre, apellido, edad)
SELECT nombre, apellido, edad
FROM personas;
DROP TABLE personas;
ALTER TABLE personas2 RENAME TO personas;
/*SE CREA UNA TABLA CON TRES CAMPOS, NOMBRE, APELLIDO Y EDAD, Y SE INSERTAN LOS DATOS DE LA TABLA PERSONAS EN LA TABLA PERSONAS2, LUEGO SE ELIMINA LA TABLA PERSONAS Y SE RENOMBRA LA TABLA PERSONAS2 A PERSONAS*/

CREATE TABLE productos (
    NOMBRE TEXT NOT NULL,
    PRECIO REAL NOT NULL,
    CODIGO TEXT UNIQUE
);
INSERT INTO productos
VALUES ('CAMISA', 1000.00, 'CAM-001'),
('PANTALÓN', 2000.00, 'PAN-001'),
('CAMISA XL', 1000.00, 'CAM-002');
/*SE CREA UNA TABLA CON TRES CAMPOS, NOMBRE, PRECIO Y CODIGO, HACIENDO QUE LOS CAMPOS NOMBRE Y PRECIO NO SEAN NULOS Y QUE EL CAMPO CODIGO SEA UNICO, LUEGO SE INSERTAN TRES REGISTROS EN LA TABLA*/

CREATE TABLE productos (
    nombre TEXT NOT NULL,
    precio REAL NOT NULL,
    stock INTEGER CHECK (stock > 0)
);
INSERT INTO productos VALUES
('CAMISA', 1000.00, 10),
('PANTALÓN', 2000.00, 5),
('CAMISA XL', 1000.00, 3);
/*SE CREA UNA TABLA CON TRES CAMPOS, NOMBRE, PRECIO Y STOCK, HACIENDO QUE LOS CAMPOS NOMBRE Y PRECIO NO SEAN NULOS Y QUE EL CAMPO STOCK SEA MAYOR A 0, LUEGO SE INSERTAN TRES REGISTROS EN LA TABLA*/

CREATE TABLE posts (
    ID INT PRIMARY KEY,
    TITLE TEXT,
    CONTENT TEXT 
);
INSERT INTO posts VALUES
(1, 'Introducción', '¡Bienvenido al mundo de la programación!'),
(2, 'Primeros Pasos', 'Sumérgete en los conceptos básicos de la programación.'),
(3, 'Temas Avanzados', 'Explora conceptos y técnicas avanzadas en programación.');
/*SE CREA UNA TABLA CON TRES CAMPOS, ID, TITLE Y CONTENT, HACIENDO QUE EL CAMPO ID SEA LA CLAVE PRIMARIA, LUEGO SE INSERTAN TRES REGISTROS EN LA TABLA*/

CREATE TABLE usuarios (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE TEXT NOT NULL,
    FECHA_CREACION DATE
);
INSERT INTO usuarios VALUES
('ANA', '2024-01-01'),
('GONZALO', '2024-01-02'),
('JUAN', '2024-01-03'),
('MARÍA', '2024-01-04');
/*SE CREA UNA TABLA CON TRES CAMPOS, ID, NOMBRE Y FECHA_CREACION, HACIENDO QUE EL CAMPO ID SEA LA CLAVE PRIMARIA Y SE AUTO INCREMENTE, LUEGO SE INSERTAN CUATRO REGISTROS EN LA TABLA*/

