////////////////////////////////////////
Subconsultas
////////////////////////////////////////

SELECT * FROM empleados 
WHERE sueldo < (SELECT AVG(sueldo) FROM empleados);
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA A LOS EMPLEADOS QUE TIENEN UN SUELDO MENOR AL PROMEDIO DE LOS SUELDOS DE TODOS LOS EMPLEADOS*/

SELECT * FROM empleados 
WHERE sueldo > (SELECT AVG(sueldo) 
FROM empleados 
WHERE DEPARTAMENTO LIKE 'Finanzas');
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA A LOS EMPLEADOS QUE TIENEN UN SUELDO MAYOR AL PROMEDIO DE LOS SUELDOS DE LOS EMPLEADOS DEL DEPARTAMENTO DE FINANZAS*/

SELECT * FROM empleados WHERE sueldo > (SELECT AVG(sueldo) FROM empleados 
WHERE DEPARTAMENTO LIKE 'Finanzas');
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA A LOS EMPLEADOS QUE TIENEN UN SUELDO MAYOR AL PROMEDIO DE LOS SUELDOS DE LOS EMPLEADOS DEL DEPARTAMENTO DE FINANZAS*/

SELECT * FROM NOTAS 
WHERE NOTAS > (SELECT AVG(NOTAS)
FROM NOTAS);
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA A LOS ALUMNOS QUE TIENEN UNA NOTA MAYOR AL PROMEDIO DE LAS NOTAS DE TODOS LOS ALUMNOS*/

SELECT nombre FROM estudiantes
WHERE estudiante_id IN (SELECT estudiante_id 
FROM promedios WHERE promedio_notas > 50);
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA A LOS ESTUDIANTES QUE TIENEN UN PROMEDIO DE NOTAS MAYOR A 50*/

SELECT NOMBRE AS nombres_seleccionados FROM libros 
WHERE LIBRO_ID IN
(SELECT LIBRO_ID FROM valoraciones 
WHERE VALORACION_PROMEDIO > 4)
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA A LOS LIBROS QUE TIENEN UNA VALORACION PROMEDIO MAYOR A 4*/

SELECT NOMBRE AS nombres_pacientes 
FROM pacientes
WHERE PACIENTE_ID IN (SELECT PACIENTE_ID 
FROM consultas 
WHERE FECHA_CONSULTA < '2023-05-16')
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA A LOS PACIENTES QUE HAN TENIDO CONSULTAS ANTES DE LA FECHA 2023-05-16*/

SELECT AVG (total_ventas) AS promedio_ventas 
FROM (SELECT EMPLEADO_ID, SUM(monto) AS total_ventas 
FROM ventas GROUP BY EMPLEADO_ID);
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA EL PROMEDIO DE LAS VENTAS DE CADA EMPLEADO*/

SELECT AVG (total_ventas) AS promedio_ventas 
FROM (SELECT EMPLEADO_ID, SUM(monto) AS total_ventas 
FROM ventas GROUP BY EMPLEADO_ID);
/*SE REALIZA UN CONSULTA DENTRO DE OTRA, DONDE SE BUSCA EL PROMEDIO DE LAS VENTAS DE CADA EMPLEADO*/

